import type {
  GraphAxes,
  SectionDefinition,
  SectionVisualDefinition,
  TileDefinition,
} from './types'

export const GAME_TITLE = 'Graphbound'
export const AXIS_MAX = 10
export const PLOT_DURATION_MS = 680

export const DEFAULT_AXES: GraphAxes = {
  x: { min: 0, max: AXIS_MAX, tickStep: 1 },
  y: { min: 0, max: AXIS_MAX, tickStep: 1 },
}

export const DEFAULT_SECTION_VISUAL: Required<SectionVisualDefinition> = {
  terrainWidth: 560,
  terrainHeight: 318,
  boardX: 42,
  boardY: 20,
  boardWidth: 334,
  boardHeight: 278,
  graphX: 44,
  graphY: 18,
  graphWidth: 210,
  graphHeight: 210,
  equationY: 248,
  slotSize: 42,
  tokenGap: 10,
}

const TILE_ROLE_FILLS = {
  variable: '#f9d36d',
  number: '#ffd3aa',
  operator: '#f2dd9c',
} as const

const PENCIL = '#48382a'

function normalizeCanonicalExpression(expression: string): string {
  return expression.replace(/\s+/g, ' ').trim().toLowerCase()
}

function assertUniqueGoalSolutions(sections: SectionDefinition[]): void {
  const seen = new Map<string, { sectionId: string; goalId: string }>()

  for (const section of sections) {
    for (const goal of section.goals) {
      if (!goal.canonicalExpression) {
        continue
      }

      const normalized = normalizeCanonicalExpression(goal.canonicalExpression)
      const duplicate = seen.get(normalized)

      if (duplicate) {
        throw new Error(
          `Duplicate canonical puzzle solution "${goal.canonicalExpression}" on ${section.id}:${goal.id}; already used by ${duplicate.sectionId}:${duplicate.goalId}`,
        )
      }

      seen.set(normalized, { sectionId: section.id, goalId: goal.id })
    }
  }
}

export const TILE_DEFINITIONS: Record<string, TileDefinition> = {
  x: { id: 'x', label: 'x', fill: TILE_ROLE_FILLS.variable, text: PENCIL, role: 'variable' },
  '2': { id: '2', label: '2', fill: TILE_ROLE_FILLS.number, text: PENCIL, role: 'number' },
  '5': { id: '5', label: '5', fill: TILE_ROLE_FILLS.number, text: PENCIL, role: 'number' },
  '1': { id: '1', label: '1', fill: TILE_ROLE_FILLS.number, text: PENCIL, role: 'number' },
  '0': { id: '0', label: '0', fill: TILE_ROLE_FILLS.number, text: PENCIL, role: 'number' },
  '+': { id: '+', label: '+', fill: TILE_ROLE_FILLS.operator, text: PENCIL, role: 'operator' },
  '-': { id: '-', label: '-', fill: TILE_ROLE_FILLS.operator, text: PENCIL, role: 'operator' },
}

export const SECTIONS: SectionDefinition[] = [
  {
    id: 'sprout',
    title: 'Sprout',
    blurb: 'Place x to sketch the very first line and wake the next graph.',
    accent: '#6bb9b2',
    world: { x: 0, y: 24 },
    visual: {
      terrainWidth: 520,
      terrainHeight: 298,
      boardX: 30,
      boardWidth: 320,
      boardHeight: 258,
      graphX: 48,
      graphY: 18,
      graphWidth: 206,
      graphHeight: 206,
      equationY: 230,
    },
    rewardTileId: '2',
    initialUnlocked: true,
    equation: [{ type: 'slot', slotId: 'seed' }],
    slots: [{ id: 'seed', allowedTiles: ['x'], label: 'variable' }],
    goals: [
      {
        id: 'path-ridge',
        label: 'Wake the ridge path',
        shape: 'heart',
        edge: 'top',
        min: 9.5,
        max: 10,
        unlocks: ['ridge'],
        color: '#ef9551',
        canonicalExpression: 'x',
      },
    ],
  },
  {
    id: 'ridge',
    title: 'Ridge',
    blurb: 'A fixed + waits here. Add the new number tile to tilt the path upward.',
    accent: '#eb9b6f',
    world: { x: 560, y: 12 },
    axes: {
      x: { min: 0, max: 10, tickStep: 1 },
      y: { min: -2, max: 10, tickStep: 1 },
    },
    visual: {
      terrainWidth: 622,
      terrainHeight: 320,
      boardX: 132,
      boardY: 22,
      boardWidth: 334,
      boardHeight: 272,
      graphX: 44,
      graphY: 18,
      graphWidth: 210,
      graphHeight: 194,
      equationY: 244,
    },
    rewardTileId: '+',
    equation: [
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'lift' },
    ],
    slots: [{ id: 'lift', allowedTiles: ['2', '5'], label: 'number' }],
    goals: [
      {
        id: 'path-orchard',
        label: 'Open the orchard',
        shape: 'circle',
        edge: 'top',
        min: 7.6,
        max: 8.4,
        unlocks: ['orchard'],
        color: '#eb7eb5',
        canonicalExpression: 'x + 2',
      },
    ],
    entryPath: [
      { x: 180, y: 0 },
      { x: 180, y: 22 },
      { x: 176, y: 40 },
    ],
  },
  {
    id: 'orchard',
    title: 'Orchard',
    blurb: 'This board branches. 2x reveals the cove, and x + 5 reaches the canopy later.',
    accent: '#9c86d6',
    world: { x: 1080, y: 0 },
    axes: {
      x: { min: 0, max: 10, tickStep: 1 },
      y: { min: 0, max: 12, tickStep: 1 },
    },
    visual: {
      terrainWidth: 664,
      terrainHeight: 346,
      boardX: 110,
      boardY: 24,
      boardWidth: 352,
      boardHeight: 286,
      graphX: 48,
      graphY: 18,
      graphWidth: 222,
      graphHeight: 208,
      equationY: 252,
    },
    equation: [
      { type: 'slot', slotId: 'lead' },
      { type: 'slot', slotId: 'middle' },
      { type: 'slot', slotId: 'tail' },
      { type: 'slot', slotId: 'cleanup' },
    ],
    slots: [
      { id: 'lead', allowedTiles: ['2', 'x'], label: 'lead token' },
      { id: 'middle', allowedTiles: ['x', '+'], label: 'middle token' },
      { id: 'tail', allowedTiles: ['2', '5', '+'], label: 'tail token' },
      { id: 'cleanup', allowedTiles: ['+'], label: 'cleanup token' },
    ],
    goals: [
      {
        id: 'path-cove',
        label: 'Open the cove',
        shape: 'x',
        edge: 'top',
        min: 5.8,
        max: 6.2,
        unlocks: ['cove'],
        color: '#3f72f0',
        canonicalExpression: '2x',
      },
      {
        id: 'path-canopy',
        label: 'Reach the canopy route',
        shape: 'star',
        edge: 'top',
        min: 6.6,
        max: 7.4,
        unlocks: ['canopy'],
        color: '#a764f4',
        canonicalExpression: 'x + 5',
      },
    ],
    entryPath: [
      { x: 178, y: 0 },
      { x: 178, y: 24 },
      { x: 174, y: 42 },
    ],
  },
  {
    id: 'cove',
    title: 'Cove',
    blurb: 'A calm constant line earns the 5 tile and opens the lower branch.',
    accent: '#8db6d9',
    world: { x: 1120, y: 528 },
    axes: {
      x: { min: -5, max: 5, tickStep: 1 },
      y: { min: -3, max: 4, tickStep: 1 },
    },
    visual: {
      terrainWidth: 514,
      terrainHeight: 364,
      boardX: 42,
      boardY: 46,
      boardWidth: 314,
      boardHeight: 248,
      graphX: 34,
      graphY: 12,
      graphWidth: 214,
      graphHeight: 170,
      equationY: 216,
    },
    rewardTileId: '5',
    equation: [{ type: 'slot', slotId: 'still' }],
    slots: [{ id: 'still', allowedTiles: ['2', '5'], label: 'number' }],
    goals: [
      {
        id: 'path-basin',
        label: 'Open the basin',
        shape: 'circle',
        edge: 'right',
        min: 1.6,
        max: 2.4,
        unlocks: ['basin'],
        color: '#3f72f0',
        canonicalExpression: '2',
      },
    ],
    entryPath: [
      { x: 0, y: 140 },
      { x: 22, y: 140 },
      { x: 46, y: 126 },
    ],
  },
  {
    id: 'basin',
    title: 'Basin',
    blurb: 'Let the number hug x so the line shoots sharply upward.',
    accent: '#7ba5bf',
    world: { x: 1690, y: 536 },
    axes: {
      x: { min: 0, max: 2, tickStep: 0.5 },
      y: { min: 0, max: 10, tickStep: 1 },
    },
    equation: [
      { type: 'slot', slotId: 'factor' },
      { type: 'slot', slotId: 'variable' },
    ],
    slots: [
      { id: 'factor', allowedTiles: ['5', 'x'], label: 'first factor' },
      { id: 'variable', allowedTiles: ['x'], label: 'second factor' },
    ],
    goals: [
      {
        id: 'path-gallery',
        label: 'Wake the gallery',
        shape: 'heart',
        edge: 'top',
        min: 1.86,
        max: 2,
        unlocks: ['gallery'],
        color: '#f19d57',
        canonicalExpression: '5x',
      },
    ],
  },
  {
    id: 'gallery',
    title: 'Gallery',
    blurb: 'Build a calm horizontal line to reveal the center of the world.',
    accent: '#cc8eb4',
    world: { x: 2250, y: 486 },
    axes: {
      x: { min: 0, max: 5, tickStep: 1 },
      y: { min: 5, max: 9, tickStep: 1 },
    },
    equation: [
      { type: 'fixed', value: '2' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'step' },
    ],
    slots: [{ id: 'step', allowedTiles: ['5'], label: 'step' }],
    goals: [
      {
        id: 'path-crossroads',
        label: 'Reveal the center crossroads',
        shape: 'star',
        edge: 'right',
        min: 6.6,
        max: 7.4,
        unlocks: ['crossroads'],
        color: '#e18ea8',
        canonicalExpression: '7',
      },
    ],
  },
  {
    id: 'canopy',
    title: 'Canopy',
    blurb: 'The upper branch steepens into a higher line and finally grants minus.',
    accent: '#7eb17d',
    world: { x: 1126, y: -532 },
    axes: {
      x: { min: 0, max: 5, tickStep: 1 },
      y: { min: 5, max: 9, tickStep: 1 },
    },
    visual: {
      terrainWidth: 528,
      terrainHeight: 430,
      boardX: 94,
      boardY: 24,
      boardWidth: 262,
      boardHeight: 344,
      graphX: 36,
      graphY: 16,
      graphWidth: 186,
      graphHeight: 250,
      equationY: 304,
      slotSize: 38,
    },
    rewardTileId: '-',
    equation: [
      { type: 'fixed', value: '2' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'lift' },
    ],
    slots: [{ id: 'lift', allowedTiles: ['5'], label: 'lift term' }],
    goals: [
      {
        id: 'path-minus',
        label: 'Win the minus tile',
        shape: 'x',
        edge: 'top',
        min: 1.9,
        max: 2.1,
        unlocks: [],
        color: '#5bc8ff',
        canonicalExpression: '2x + 5',
      },
    ],
    entryPath: [
      { x: 176, y: 0 },
      { x: 176, y: 22 },
      { x: 168, y: 40 },
    ],
  },
  {
    id: 'crossroads',
    title: 'Crossroads',
    blurb: 'This middle board opens one branch at a time as your tile kit grows.',
    accent: '#8f86c9',
    world: { x: 1990, y: -74 },
    axes: {
      x: { min: -2, max: 10, tickStep: 1 },
      y: { min: -2, max: 10, tickStep: 1 },
    },
    visual: {
      terrainWidth: 640,
      terrainHeight: 360,
      boardX: 94,
      boardY: 18,
      boardWidth: 366,
      boardHeight: 310,
      graphX: 46,
      graphY: 16,
      graphWidth: 244,
      graphHeight: 244,
      equationY: 278,
    },
    equation: [
      { type: 'slot', slotId: 'first' },
      { type: 'slot', slotId: 'second' },
      { type: 'slot', slotId: 'third' },
      { type: 'slot', slotId: 'fourth' },
    ],
    slots: [
      { id: 'first', allowedTiles: ['2', '1', '5'], label: 'first token' },
      { id: 'second', allowedTiles: ['+', '-', '0'], label: 'second token' },
      { id: 'third', allowedTiles: ['2', '5', 'x', '+'], label: 'third token' },
      { id: 'fourth', allowedTiles: ['+'], label: 'cleanup token' },
    ],
    goals: [
      {
        id: 'path-eastreach',
        label: 'Open the east branch',
        shape: 'heart',
        edge: 'right',
        min: 3.7,
        max: 4.3,
        unlocks: ['eastreach'],
        color: '#e7904e',
        canonicalExpression: '4',
      },
      {
        id: 'path-arch',
        label: 'Open the west branch',
        shape: 'circle',
        edge: 'bottom',
        min: 3.6,
        max: 4.4,
        unlocks: ['arch'],
        color: '#b07cf3',
        canonicalExpression: '2 - x',
      },
      {
        id: 'path-southreach',
        label: 'Open the south branch',
        shape: 'x',
        edge: 'top',
        min: 8.7,
        max: 9.3,
        unlocks: ['southreach'],
        color: '#58b9ff',
        canonicalExpression: '1 + x',
      },
      {
        id: 'path-northreach',
        label: 'Open the north branch',
        shape: 'star',
        edge: 'right',
        min: 4.7,
        max: 5.3,
        unlocks: ['northreach'],
        color: '#f28eb1',
        canonicalExpression: '5',
      },
    ],
  },
  {
    id: 'eastreach',
    title: 'Eastreach',
    blurb: 'A small parabola is the first curve in the world.',
    accent: '#d9aa78',
    world: { x: 2672, y: -62 },
    axes: {
      x: { min: 0, max: 1.5, tickStep: 0.25 },
      y: { min: 0, max: 3, tickStep: 0.5 },
    },
    equation: [
      { type: 'fixed', value: 'x²' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'boost' },
    ],
    slots: [{ id: 'boost', allowedTiles: ['2'], label: 'boost' }],
    goals: [
      {
        id: 'path-eastvault',
        label: 'Open the east vault',
        shape: 'circle',
        edge: 'top',
        min: 0.92,
        max: 1.08,
        unlocks: ['eastvault'],
        color: '#f3a06d',
        canonicalExpression: 'x^2 + 2',
      },
    ],
  },
  {
    id: 'eastvault',
    title: 'East Vault',
    blurb: 'A taller parabola finally grants the 1 tile.',
    accent: '#e29d78',
    world: { x: 3248, y: -18 },
    axes: {
      x: { min: 0, max: 2.5, tickStep: 0.5 },
      y: { min: 0, max: 9, tickStep: 1 },
    },
    rewardTileId: '1',
    equation: [
      { type: 'fixed', value: 'x²' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'height' },
    ],
    slots: [{ id: 'height', allowedTiles: ['5'], label: 'height' }],
    goals: [
      {
        id: 'path-one',
        label: 'Win the one tile',
        shape: 'star',
        edge: 'top',
        min: 1.9,
        max: 2.1,
        unlocks: [],
        color: '#ef9f6f',
        canonicalExpression: 'x^2 + 5',
      },
    ],
  },
  {
    id: 'arch',
    title: 'Arch',
    blurb: 'Subtract x from 5 to bend the line back down.',
    accent: '#a685d8',
    world: { x: 1840, y: -706 },
    axes: {
      x: { min: -1, max: 4, tickStep: 1 },
      y: { min: 0, max: 6, tickStep: 1 },
    },
    equation: [
      { type: 'fixed', value: '5' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'fall' },
    ],
    slots: [{ id: 'fall', allowedTiles: ['x'], label: 'fall' }],
    goals: [
      {
        id: 'path-mire',
        label: 'Open the mire',
        shape: 'heart',
        edge: 'right',
        min: 0.7,
        max: 1.3,
        unlocks: ['mire'],
        color: '#9e7bef',
        canonicalExpression: '5 - x',
      },
    ],
  },
  {
    id: 'mire',
    title: 'Mire',
    blurb: 'Now mix multiplication and subtraction in the same equation.',
    accent: '#9188d9',
    world: { x: 1280, y: -908 },
    axes: {
      x: { min: 0, max: 2, tickStep: 0.5 },
      y: { min: 0, max: 5, tickStep: 1 },
    },
    equation: [
      { type: 'slot', slotId: 'crest' },
      { type: 'fixed', value: '-' },
      { type: 'fixed', value: 'x²' },
    ],
    slots: [{ id: 'crest', allowedTiles: ['5'], label: 'crest' }],
    goals: [
      {
        id: 'path-hollow',
        label: 'Open the hollow',
        shape: 'x',
        edge: 'right',
        min: 0.7,
        max: 1.3,
        unlocks: ['hollow'],
        color: '#a870f3',
        canonicalExpression: '5 - x^2',
      },
    ],
  },
  {
    id: 'hollow',
    title: 'Hollow',
    blurb: 'A downward parabola waits here as a late revisit.',
    accent: '#7f7cc0',
    world: { x: 648, y: -628 },
    axes: {
      x: { min: 0, max: 4, tickStep: 1 },
      y: { min: -5, max: 11, tickStep: 1 },
    },
    equation: [
      { type: 'fixed', value: 'x²' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'dip' },
    ],
    slots: [{ id: 'dip', allowedTiles: ['5'], label: 'dip' }],
    goals: [
      {
        id: 'path-hollow-finish',
        label: 'Finish the hollow',
        shape: 'circle',
        edge: 'top',
        min: 4,
        max: 4,
        unlocks: [],
        color: '#8f86d6',
        canonicalExpression: 'x^2 - 5',
      },
    ],
  },
  {
    id: 'southreach',
    title: 'Southreach',
    blurb: 'The 1 tile opens a low horizontal line.',
    accent: '#6ea7de',
    world: { x: 2022, y: 612 },
    axes: {
      x: { min: -2, max: 6, tickStep: 1 },
      y: { min: -2, max: 4, tickStep: 1 },
    },
    equation: [
      { type: 'fixed', value: '1' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'drop' },
    ],
    slots: [{ id: 'drop', allowedTiles: ['2'], label: 'drop' }],
    goals: [
      {
        id: 'path-southvault',
        label: 'Open the south vault',
        shape: 'heart',
        edge: 'right',
        min: -1.35,
        max: -0.65,
        unlocks: ['southvault'],
        color: '#5bb2ff',
        canonicalExpression: '-1',
      },
    ],
  },
  {
    id: 'southvault',
    title: 'South Vault',
    blurb: 'Use the same number twice to make ten and finally unlock 0.',
    accent: '#63a8dd',
    world: { x: 2588, y: 812 },
    axes: {
      x: { min: 0, max: 5, tickStep: 1 },
      y: { min: 0, max: 10, tickStep: 1 },
    },
    rewardTileId: '0',
    equation: [
      { type: 'fixed', value: '5' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'right' },
    ],
    slots: [{ id: 'right', allowedTiles: ['5'], label: 'right addend' }],
    goals: [
      {
        id: 'path-zero',
        label: 'Win the zero tile',
        shape: 'star',
        edge: 'left',
        min: 9.7,
        max: 10,
        unlocks: [],
        color: '#67b4ef',
        canonicalExpression: '10',
      },
    ],
  },
  {
    id: 'northreach',
    title: 'Northreach',
    blurb: 'Concatenate 1 and 0, then attach x for a steep final branch.',
    accent: '#d28e7d',
    world: { x: 2468, y: -664 },
    axes: {
      x: { min: 0, max: 1, tickStep: 0.1 },
      y: { min: 0, max: 10, tickStep: 1 },
    },
    equation: [
      { type: 'slot', slotId: 'tens' },
      { type: 'slot', slotId: 'ones' },
      { type: 'fixed', value: 'x' },
    ],
    slots: [
      { id: 'tens', allowedTiles: ['1'], label: 'tens digit' },
      { id: 'ones', allowedTiles: ['0'], label: 'ones digit' },
    ],
    goals: [
      {
        id: 'path-loft',
        label: 'Open the loft',
        shape: 'circle',
        edge: 'top',
        min: 0.94,
        max: 1,
        unlocks: ['loft'],
        color: '#de907c',
        canonicalExpression: '10x',
      },
    ],
  },
  {
    id: 'loft',
    title: 'Loft',
    blurb: 'Slide a two-digit line down toward the weave branch.',
    accent: '#cf9479',
    world: { x: 3080, y: -916 },
    axes: {
      x: { min: 0, max: 4, tickStep: 1 },
      y: { min: -5, max: 11, tickStep: 1 },
    },
    equation: [
      { type: 'fixed', value: '1' },
      { type: 'fixed', value: '0' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'drop' },
    ],
    slots: [{ id: 'drop', allowedTiles: ['x'], label: 'drop' }],
    goals: [
      {
        id: 'path-weave',
        label: 'Open the weave',
        shape: 'x',
        edge: 'right',
        min: 5.7,
        max: 6.3,
        unlocks: ['weave'],
        color: '#dd9b77',
        canonicalExpression: '10 - x',
      },
    ],
  },
  {
    id: 'weave',
    title: 'Weave',
    blurb: 'Now the numbers wrap into both a coefficient and a two-digit offset.',
    accent: '#d68c6e',
    world: { x: 3642, y: -664 },
    axes: {
      x: { min: 0, max: 3, tickStep: 0.5 },
      y: { min: 0, max: 10, tickStep: 1 },
    },
    equation: [
      { type: 'slot', slotId: 'digitA' },
      { type: 'slot', slotId: 'digitB' },
      { type: 'fixed', value: '-' },
      { type: 'fixed', value: 'x²' },
    ],
    slots: [
      { id: 'digitA', allowedTiles: ['1'], label: 'tens digit' },
      { id: 'digitB', allowedTiles: ['0'], label: 'ones digit' },
    ],
    goals: [
      {
        id: 'path-cellar',
        label: 'Open the cellar',
        shape: 'heart',
        edge: 'right',
        min: 0.7,
        max: 1.3,
        unlocks: ['cellar'],
        color: '#d78c70',
        canonicalExpression: '10 - x^2',
      },
    ],
  },
  {
    id: 'cellar',
    title: 'Cellar',
    blurb: 'Use the two-digit subtraction again, but on a parabola this time.',
    accent: '#d58b77',
    world: { x: 4210, y: -288 },
    axes: {
      x: { min: 0, max: 4, tickStep: 1 },
      y: { min: -2, max: 6, tickStep: 1 },
    },
    equation: [
      { type: 'fixed', value: 'x²' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'digitA' },
      { type: 'slot', slotId: 'digitB' },
    ],
    slots: [
      { id: 'digitA', allowedTiles: ['1'], label: 'tens digit' },
      { id: 'digitB', allowedTiles: ['0'], label: 'ones digit' },
    ],
    goals: [
      {
        id: 'path-finale',
        label: 'Open the finale',
        shape: 'circle',
        edge: 'top',
        min: 4,
        max: 4,
        unlocks: ['finale'],
        color: '#d69280',
        canonicalExpression: 'x^2 - 10',
      },
    ],
  },
  {
    id: 'finale',
    title: 'Finale',
    blurb: 'The last graph mixes a coefficient with a parabola and a two-digit shift.',
    accent: '#c78882',
    world: { x: 4788, y: -52 },
    axes: {
      x: { min: 0, max: 4, tickStep: 1 },
      y: { min: -2, max: 8, tickStep: 1 },
    },
    equation: [
      { type: 'fixed', value: '2' },
      { type: 'fixed', value: 'x²' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'digitA' },
      { type: 'slot', slotId: 'digitB' },
    ],
    slots: [
      { id: 'digitA', allowedTiles: ['1'], label: 'tens digit' },
      { id: 'digitB', allowedTiles: ['0'], label: 'ones digit' },
    ],
    goals: [
      {
        id: 'path-victory',
        label: 'Finish the whole world',
        shape: 'star',
        edge: 'top',
        min: 2.9,
        max: 3.1,
        unlocks: [],
        color: '#cf8b8e',
        canonicalExpression: '2x^2 - 10',
      },
    ],
  },
]

assertUniqueGoalSolutions(SECTIONS)
