import type {
  GraphAxes,
  SectionDefinition,
  SectionVisualDefinition,
  TileDefinition,
} from './types'

export const GAME_TITLE = 'Graphbound'
export const AXIS_MAX = 10
export const PLOT_DURATION_MS = 680

export const DEFAULT_AXES: GraphAxes = {
  x: { min: 0, max: AXIS_MAX, tickStep: 1 },
  y: { min: 0, max: AXIS_MAX, tickStep: 1 },
}

export const DEFAULT_SECTION_VISUAL: Required<SectionVisualDefinition> = {
  terrainWidth: 560,
  terrainHeight: 318,
  boardX: 42,
  boardY: 20,
  boardWidth: 334,
  boardHeight: 278,
  graphX: 44,
  graphY: 18,
  graphWidth: 210,
  graphHeight: 210,
  equationY: 248,
  slotSize: 42,
  tokenGap: 10,
}

const TILE_ROLE_FILLS = {
  variable: '#f9d36d',
  number: '#ffd3aa',
  operator: '#f2dd9c',
} as const

const PENCIL = '#48382a'

function normalizeCanonicalExpression(expression: string): string {
  return expression.replace(/\s+/g, ' ').trim().toLowerCase()
}

function assertUniqueGoalSolutions(sections: SectionDefinition[]): void {
  const seen = new Map<string, { sectionId: string; goalId: string }>()

  for (const section of sections) {
    for (const goal of section.goals) {
      if (!goal.canonicalExpression) {
        continue
      }

      const normalized = normalizeCanonicalExpression(goal.canonicalExpression)
      const duplicate = seen.get(normalized)

      if (duplicate) {
        throw new Error(
          `Duplicate canonical puzzle solution "${goal.canonicalExpression}" on ${section.id}:${goal.id}; already used by ${duplicate.sectionId}:${duplicate.goalId}`,
        )
      }

      seen.set(normalized, { sectionId: section.id, goalId: goal.id })
    }
  }
}

export const TILE_DEFINITIONS: Record<string, TileDefinition> = {
  x: { id: 'x', label: 'x', fill: TILE_ROLE_FILLS.variable, text: PENCIL, role: 'variable' },
  'θ': { id: 'θ', label: 'Θ', fill: TILE_ROLE_FILLS.variable, text: PENCIL, role: 'variable' },
  '2': { id: '2', label: '2', fill: TILE_ROLE_FILLS.number, text: PENCIL, role: 'number' },
  '5': { id: '5', label: '5', fill: TILE_ROLE_FILLS.number, text: PENCIL, role: 'number' },
  '1': { id: '1', label: '1', fill: TILE_ROLE_FILLS.number, text: PENCIL, role: 'number' },
  '0': { id: '0', label: '0', fill: TILE_ROLE_FILLS.number, text: PENCIL, role: 'number' },
  '+': { id: '+', label: '+', fill: TILE_ROLE_FILLS.operator, text: PENCIL, role: 'operator' },
  '-': { id: '-', label: '-', fill: TILE_ROLE_FILLS.operator, text: PENCIL, role: 'operator' },
}

export const SECTIONS: SectionDefinition[] = [
  {
    id: 'sprout',
    title: 'Sprout',
    blurb: 'Place x to sketch the very first line and wake the next graph.',
    accent: '#6bb9b2',
    world: { x: 0, y: 24 },
    visual: {
      terrainWidth: 520,
      terrainHeight: 298,
      boardX: 30,
      boardWidth: 320,
      boardHeight: 258,
      graphX: 48,
      graphY: 18,
      graphWidth: 206,
      graphHeight: 206,
      equationY: 230,
    },
    rewardTileId: '2',
    initialUnlocked: true,
    equation: [{ type: 'slot', slotId: 'seed' }],
    slots: [{ id: 'seed', allowedTiles: ['x'], label: 'variable' }],
    goals: [
      {
        id: 'path-ridge',
        label: 'Wake the ridge path',
        shape: 'heart',
        edge: 'top',
        min: 9.5,
        max: 10,
        unlocks: ['ridge'],
        color: '#ef9551',
        canonicalExpression: 'x',
      },
    ],
  },
  {
    id: 'ridge',
    title: 'Ridge',
    blurb: 'A fixed + waits here. Add the new number tile to tilt the path upward.',
    accent: '#eb9b6f',
    world: { x: 560, y: 12 },
    axes: {
      x: { min: 0, max: 10, tickStep: 1 },
      y: { min: -2, max: 10, tickStep: 1 },
    },
    visual: {
      terrainWidth: 622,
      terrainHeight: 320,
      boardX: 132,
      boardY: 22,
      boardWidth: 334,
      boardHeight: 272,
      graphX: 44,
      graphY: 18,
      graphWidth: 210,
      graphHeight: 194,
      equationY: 244,
    },
    rewardTileId: '+',
    equation: [
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'lift' },
    ],
    slots: [{ id: 'lift', allowedTiles: ['2', '5'], label: 'number' }],
    goals: [
      {
        id: 'path-orchard',
        label: 'Open the orchard',
        shape: 'triangle',
        edge: 'top',
        min: 7.6,
        max: 8.4,
        unlocks: ['orchard'],
        color: '#eb7eb5',
        canonicalExpression: 'x + 2',
      },
    ],
    entryPath: [
      { x: 180, y: 0 },
      { x: 180, y: 22 },
      { x: 176, y: 40 },
    ],
  },
  {
    id: 'orchard',
    title: 'Orchard',
    blurb: 'This board branches. 2x reveals the cove, and x + 5 reaches the canopy later.',
    accent: '#9c86d6',
    world: { x: 1080, y: 0 },
    axes: {
      x: { min: 0, max: 10, tickStep: 1 },
      y: { min: 0, max: 12, tickStep: 1 },
    },
    visual: {
      terrainWidth: 664,
      terrainHeight: 346,
      boardX: 110,
      boardY: 24,
      boardWidth: 352,
      boardHeight: 286,
      graphX: 48,
      graphY: 18,
      graphWidth: 222,
      graphHeight: 208,
      equationY: 252,
    },
    equation: [
      { type: 'slot', slotId: 'lead' },
      { type: 'slot', slotId: 'middle' },
      { type: 'slot', slotId: 'tail' },
      { type: 'slot', slotId: 'cleanup' },
    ],
    slots: [
      { id: 'lead', allowedTiles: ['2', 'x'], label: 'lead token' },
      { id: 'middle', allowedTiles: ['x', '+'], label: 'middle token' },
      { id: 'tail', allowedTiles: ['2', '5', '+'], label: 'tail token' },
      { id: 'cleanup', allowedTiles: ['+'], label: 'cleanup token' },
    ],
    goals: [
      {
        id: 'path-cove',
        label: 'Open the cove',
        shape: 'x',
        edge: 'top',
        min: 5.7,
        max: 6.1,
        unlocks: ['cove'],
        color: '#3f72f0',
        canonicalExpression: '2x',
      },
      {
        id: 'path-canopy',
        label: 'Reach the canopy route',
        shape: 'star',
        edge: 'top',
        min: 6.9,
        max: 7.3,
        unlocks: ['canopy'],
        color: '#a764f4',
        canonicalExpression: 'x + 5',
      },
    ],
    entryPath: [
      { x: 178, y: 0 },
      { x: 178, y: 24 },
      { x: 174, y: 42 },
    ],
  },
  {
    id: 'cove',
    title: 'Cove',
    blurb: 'Parentheses and division arrive together: scale a line down without changing its direction.',
    accent: '#8db6d9',
    world: { x: 1280, y: 470 },
    axes: {
      x: { min: -2, max: 8, tickStep: 1 },
      y: { min: -1, max: 5, tickStep: 1 },
    },
    visual: {
      terrainWidth: 514,
      terrainHeight: 364,
      boardX: 42,
      boardY: 46,
      boardWidth: 314,
      boardHeight: 248,
      graphX: 34,
      graphY: 12,
      graphWidth: 214,
      graphHeight: 170,
      equationY: 216,
    },
    rewardTileId: '5',
    equation: [
      { type: 'fixed', value: '(' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'lift' },
      { type: 'fixed', value: ')' },
      { type: 'fixed', value: '/' },
      { type: 'fixed', value: '2' },
    ],
    slots: [{ id: 'lift', allowedTiles: ['2'], label: 'offset' }],
    goals: [
      {
        id: 'path-basin',
        label: 'Open the basin',
        shape: 'square',
        edge: 'right',
        min: 4.9,
        max: 5.1,
        unlocks: ['basin'],
        color: '#3f72f0',
        canonicalExpression: '(x + 2) / 2',
      },
    ],
    entryPath: [
      { x: 0, y: 140 },
      { x: 22, y: 140 },
      { x: 46, y: 126 },
    ],
  },
  {
    id: 'basin',
    title: 'Basin',
    blurb: 'A second fraction turns multiplication into a gentler curve toward the gallery.',
    accent: '#7ba5bf',
    world: { x: 1940, y: 600 },
    axes: {
      x: { min: -2, max: 8, tickStep: 1 },
      y: { min: -1, max: 5, tickStep: 1 },
    },
    equation: [
      { type: 'fixed', value: '(' },
      { type: 'slot', slotId: 'factor' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: ')' },
      { type: 'fixed', value: '/' },
      { type: 'fixed', value: '(' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '+' },
      { type: 'fixed', value: '5' },
      { type: 'fixed', value: ')' },
    ],
    slots: [{ id: 'factor', allowedTiles: ['2', '5'], label: 'numerator factor' }],
    goals: [
      {
        id: 'path-gallery',
        label: 'Wake the gallery',
        shape: 'heart',
        edge: 'right',
        min: 2.95,
        max: 3.2,
        unlocks: ['gallery'],
        color: '#f19d57',
        canonicalExpression: '(5x) / (x + 5)',
      },
    ],
  },
  {
    id: 'gallery',
    title: 'Gallery',
    blurb: 'Absolute value introduces corners and symmetry without adding any new tiles yet.',
    accent: '#cc8eb4',
    world: { x: 2340, y: 330 },
    axes: {
      x: { min: -2, max: 8, tickStep: 1 },
      y: { min: -1, max: 4, tickStep: 1 },
    },
    equation: [
      { type: 'fixed', value: '|' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'offset' },
      { type: 'fixed', value: '|' },
    ],
    slots: [{ id: 'offset', allowedTiles: ['5'], label: 'offset' }],
    goals: [
      {
        id: 'path-crossroads',
        label: 'Reveal the center crossroads',
        shape: 'diamond',
        edge: 'right',
        min: 2.9,
        max: 3.1,
        unlocks: ['crossroads'],
        color: '#e18ea8',
        canonicalExpression: '|x - 5|',
      },
    ],
  },
  {
    id: 'canopy',
    title: 'Canopy',
    blurb: 'A shifted absolute value shows how corners can be lifted into brand-new routes.',
    accent: '#7eb17d',
    world: { x: 1080, y: -500 },
    axes: {
      x: { min: -2, max: 8, tickStep: 1 },
      y: { min: -1, max: 7, tickStep: 1 },
    },
    visual: {
      terrainWidth: 528,
      terrainHeight: 430,
      boardX: 94,
      boardY: 24,
      boardWidth: 262,
      boardHeight: 344,
      graphX: 36,
      graphY: 16,
      graphWidth: 186,
      graphHeight: 250,
      equationY: 304,
      slotSize: 38,
    },
    rewardTileId: '-',
    equation: [
      { type: 'fixed', value: '|' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '-' },
      { type: 'fixed', value: '5' },
      { type: 'fixed', value: '|' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'lift' },
    ],
    slots: [{ id: 'lift', allowedTiles: ['2'], label: 'lift' }],
    goals: [
      {
        id: 'path-minus',
        label: 'Win the minus tile',
        shape: 'x',
        edge: 'right',
        min: 4.8,
        max: 5.2,
        unlocks: [],
        color: '#5bc8ff',
        canonicalExpression: '|x - 5| + 2',
      },
    ],
    entryPath: [
      { x: 176, y: 0 },
      { x: 176, y: 22 },
      { x: 168, y: 40 },
    ],
  },
  {
    id: 'crossroads',
    title: 'Crossroads',
    blurb: 'This full-plane center board plants one target in each quadrant and asks you to keep returning with a better toolkit.',
    accent: '#8f86c9',
    world: { x: 1830, y: -40 },
    axes: {
      x: { min: -10, max: 10, tickStep: 5 },
      y: { min: -10, max: 10, tickStep: 5 },
    },
    visual: {
      terrainWidth: 760,
      terrainHeight: 620,
      boardX: 82,
      boardY: 18,
      boardWidth: 584,
      boardHeight: 560,
      graphX: 54,
      graphY: 16,
      graphWidth: 420,
      graphHeight: 420,
      equationY: 488,
    },
    equation: [
      { type: 'slot', slotId: 'first' },
      { type: 'slot', slotId: 'second' },
      { type: 'slot', slotId: 'third' },
      { type: 'slot', slotId: 'fourth' },
      { type: 'slot', slotId: 'fifth' },
      { type: 'slot', slotId: 'sixth' },
      { type: 'slot', slotId: 'seventh' },
    ],
    slots: [
      { id: 'first', allowedTiles: ['2', '1', '5', '0', 'x', '+', '-'], label: 'first token' },
      { id: 'second', allowedTiles: ['2', '1', '5', '0', 'x', '+', '-'], label: 'second token' },
      { id: 'third', allowedTiles: ['2', '1', '5', '0', 'x', '+', '-'], label: 'third token' },
      { id: 'fourth', allowedTiles: ['2', '1', '5', '0', 'x', '+', '-'], label: 'fourth token' },
      { id: 'fifth', allowedTiles: ['2', '1', '5', '0', 'x', '+', '-'], label: 'fifth token' },
      { id: 'sixth', allowedTiles: ['2', '1', '5', '0', 'x', '+', '-'], label: 'sixth token' },
      { id: 'seventh', allowedTiles: ['2', '1', '5', '0', 'x', '+', '-'], label: 'seventh token' },
    ],
    goals: [
      {
        id: 'path-eastreach',
        label: 'Open the northeast branch',
        shape: 'hexagon',
        edge: 'right',
        min: 4.7,
        max: 5.3,
        unlocks: ['eastreach'],
        color: '#e7904e',
        canonicalExpression: 'x - 5',
      },
      {
        id: 'path-arch',
        label: 'Open the northwest branch',
        shape: 'triangle',
        edge: 'top',
        min: -1.2,
        max: -0.8,
        unlocks: ['arch'],
        color: '#b07cf3',
        canonicalExpression: '5x + 15',
      },
      {
        id: 'path-southreach',
        label: 'Open the southwest branch',
        shape: 'x',
        edge: 'bottom',
        min: -2.7,
        max: -2.3,
        unlocks: ['southreach'],
        color: '#58b9ff',
        canonicalExpression: '0 - 2x - 15',
      },
      {
        id: 'path-northreach',
        label: 'Open the southeast branch',
        shape: 'star',
        edge: 'right',
        min: -8.2,
        max: -7.8,
        unlocks: ['northreach'],
        color: '#f28eb1',
        canonicalExpression: '2 - x',
      },
    ],
  },
  {
    id: 'eastreach',
    title: 'Eastreach',
    blurb: 'Superscripts turn the familiar line tile into the world’s first true power curve.',
    accent: '#d9aa78',
    world: { x: 2490, y: -30 },
    axes: {
      x: { min: 0, max: 1.8, tickStep: 0.3 },
      y: { min: 0, max: 3, tickStep: 0.5 },
    },
    equation: [
      { type: 'fixed', value: 'x' },
      { type: 'slot', slotId: 'power', displayStyle: 'superscript' },
    ],
    slots: [{ id: 'power', allowedTiles: ['2'], label: 'power' }],
    goals: [
      {
        id: 'path-eastvault',
        label: 'Open the east vault',
        shape: 'circle',
        edge: 'top',
        min: 1.68,
        max: 1.74,
        unlocks: ['eastvault'],
        color: '#f3a06d',
        canonicalExpression: 'x^2',
      },
    ],
  },
  {
    id: 'eastvault',
    title: 'East Vault',
    blurb: 'Another superscript curve plus a lift term rounds out the power notation.',
    accent: '#e29d78',
    world: { x: 3010, y: 20 },
    axes: {
      x: { min: 0, max: 2.5, tickStep: 0.5 },
      y: { min: 0, max: 9, tickStep: 1 },
    },
    rewardTileId: '1',
    equation: [
      { type: 'fixed', value: 'x' },
      { type: 'slot', slotId: 'power', displayStyle: 'superscript' },
      { type: 'fixed', value: '+' },
      { type: 'fixed', value: '5' },
    ],
    slots: [{ id: 'power', allowedTiles: ['2'], label: 'power' }],
    goals: [
      {
        id: 'path-one',
        label: 'Win the one tile',
        shape: 'star',
        edge: 'top',
        min: 1.9,
        max: 2.1,
        unlocks: [],
        color: '#ef9f6f',
        canonicalExpression: 'x^2 + 5',
      },
    ],
  },
  {
    id: 'arch',
    title: 'Arch',
    blurb: 'Sine appears as a soft wave, but this first version still stays inside one smooth arch.',
    accent: '#a685d8',
    world: { x: 1490, y: -730 },
    axes: {
      x: { min: 0, max: 1.6, tickStep: 0.2 },
      y: { min: 5, max: 6.2, tickStep: 0.2 },
    },
    equation: [
      { type: 'fixed', value: 'sin' },
      { type: 'fixed', value: '(' },
      { type: 'slot', slotId: 'wave' },
      { type: 'fixed', value: ')' },
      { type: 'fixed', value: '+' },
      { type: 'fixed', value: '5' },
    ],
    slots: [{ id: 'wave', allowedTiles: ['x'], label: 'wave input' }],
    goals: [
      {
        id: 'path-mire',
        label: 'Open the mire',
        shape: 'clover',
        edge: 'right',
        min: 5.95,
        max: 6.05,
        unlocks: ['mire'],
        color: '#9e7bef',
        canonicalExpression: 'sin(x) + 5',
      },
    ],
  },
  {
    id: 'mire',
    title: 'Mire',
    blurb: 'A shifted sine curve asks you to read wave phase instead of just height.',
    accent: '#9188d9',
    world: { x: 760, y: -820 },
    axes: {
      x: { min: 0, max: 2.4, tickStep: 0.4 },
      y: { min: 2, max: 3, tickStep: 0.2 },
    },
    equation: [
      { type: 'fixed', value: 'sin' },
      { type: 'fixed', value: '(' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'shift' },
      { type: 'fixed', value: ')' },
      { type: 'fixed', value: '+' },
      { type: 'fixed', value: '2' },
    ],
    displayEquation: [
      { type: 'fixed', value: 'y' },
      { type: 'fixed', value: '-' },
      { type: 'fixed', value: 'sin' },
      { type: 'fixed', value: '(' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'shift' },
      { type: 'fixed', value: ')' },
      { type: 'fixed', value: '-' },
      { type: 'fixed', value: '2' },
      { type: 'fixed', value: '=' },
      { type: 'fixed', value: '0' },
    ],
    slots: [{ id: 'shift', allowedTiles: ['2'], label: 'shift' }],
    goals: [
      {
        id: 'path-hollow',
        label: 'Open the hollow',
        shape: 'x',
        edge: 'right',
        min: 2.65,
        max: 2.8,
        unlocks: ['hollow'],
        color: '#a870f3',
        canonicalExpression: 'sin(x + 2) + 2',
      },
    ],
  },
  {
    id: 'hollow',
    title: 'Hollow',
    blurb: 'Logs feel different immediately: they grow slowly and only exist on one side of the plane.',
    accent: '#7f7cc0',
    world: { x: 240, y: -520 },
    axes: {
      x: { min: -1, max: 6, tickStep: 1 },
      y: { min: -0.2, max: 3, tickStep: 0.5 },
    },
    equation: [
      { type: 'fixed', value: 'log' },
      { type: 'fixed', value: '2', displayStyle: 'subscript' },
      { type: 'fixed', value: '(' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'shift' },
      { type: 'fixed', value: ')' },
    ],
    slots: [{ id: 'shift', allowedTiles: ['1'], label: 'shift' }],
    goals: [
      {
        id: 'path-hollow-finish',
        label: 'Finish the hollow',
        shape: 'hexagon',
        edge: 'right',
        min: 2.7,
        max: 2.9,
        unlocks: [],
        color: '#8f86d6',
        canonicalExpression: 'log_2(x + 1)',
      },
    ],
  },
  {
    id: 'southreach',
    title: 'Southreach',
    blurb: 'A subscript slot lets the log base itself become part of the puzzle.',
    accent: '#6ea7de',
    world: { x: 1580, y: 620 },
    axes: {
      x: { min: -5, max: 15, tickStep: 5 },
      y: { min: -0.5, max: 2.5, tickStep: 0.5 },
    },
    equation: [
      { type: 'fixed', value: 'log' },
      { type: 'slot', slotId: 'base', displayStyle: 'subscript' },
      { type: 'fixed', value: '(' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '+' },
      { type: 'fixed', value: '5' },
      { type: 'fixed', value: ')' },
    ],
    slots: [{ id: 'base', allowedTiles: ['2', '5'], label: 'base' }],
    goals: [
      {
        id: 'path-southvault',
        label: 'Open the south vault',
        shape: 'heart',
        edge: 'right',
        min: 1.75,
        max: 1.95,
        unlocks: ['southvault'],
        color: '#5bb2ff',
        canonicalExpression: 'log_5(x + 5)',
      },
    ],
  },
  {
    id: 'southvault',
    title: 'South Vault',
    blurb: 'Mix the absolute-value corner with a fraction to carve out a gentler final branch.',
    accent: '#63a8dd',
    world: { x: 1000, y: 840 },
    axes: {
      x: { min: 0, max: 10, tickStep: 1 },
      y: { min: 0, max: 3, tickStep: 0.5 },
    },
    rewardTileId: '0',
    equation: [
      { type: 'fixed', value: '|' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'offset' },
      { type: 'fixed', value: '|' },
      { type: 'fixed', value: '/' },
      { type: 'fixed', value: '2' },
    ],
    slots: [{ id: 'offset', allowedTiles: ['5'], label: 'offset' }],
    goals: [
      {
        id: 'path-zero',
        label: 'Win the zero tile',
        shape: 'star',
        edge: 'right',
        min: 2.45,
        max: 2.55,
        unlocks: [],
        color: '#67b4ef',
        canonicalExpression: '|x - 5| / 2',
      },
    ],
  },
  {
    id: 'northreach',
    title: 'Northreach',
    blurb: 'A mixed power-and-fraction puzzle awards the theta tile for the polar branch.',
    accent: '#d28e7d',
    world: { x: 2360, y: -520 },
    axes: {
      x: { min: 0, max: 5, tickStep: 1 },
      y: { min: 0, max: 2.2, tickStep: 0.5 },
    },
    rewardTileId: 'θ',
    equation: [
      { type: 'fixed', value: '(' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '2', displayStyle: 'superscript' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'lift' },
      { type: 'fixed', value: ')' },
      { type: 'fixed', value: '/' },
      { type: 'fixed', value: '5' },
    ],
    displayEquation: [
      { type: 'fixed', value: '5' },
      { type: 'fixed', value: 'y' },
      { type: 'fixed', value: '-' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '2', displayStyle: 'superscript' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'lift' },
      { type: 'fixed', value: '=' },
      { type: 'fixed', value: '0' },
    ],
    slots: [{ id: 'lift', allowedTiles: ['5'], label: 'lift' }],
    goals: [
      {
        id: 'path-loft',
        label: 'Open the loft',
        shape: 'circle',
        edge: 'right',
        min: 2,
        max: 2.1,
        unlocks: ['loft'],
        color: '#de907c',
        canonicalExpression: '(x^2 + 5) / 5',
      },
    ],
  },
  {
    id: 'loft',
    title: 'Loft',
    blurb: 'Polar space starts simply: the radius grows directly with theta.',
    accent: '#cf9479',
    world: { x: 2920, y: -760 },
    coordinateMode: 'polar',
    equationPrefix: 'r',
    parameterDomain: { min: 0, max: 3.1416, tickStep: 0.7854 },
    axes: {
      x: { min: -3.4, max: 3.4, tickStep: 1 },
      y: { min: -1, max: 4, tickStep: 1 },
    },
    equation: [{ type: 'slot', slotId: 'theta' }],
    slots: [{ id: 'theta', allowedTiles: ['θ'], label: 'theta input' }],
    goals: [
      {
        id: 'path-weave',
        label: 'Open the weave',
        shape: 'x',
        edge: 'left',
        min: -0.2,
        max: 0.2,
        unlocks: ['weave'],
        color: '#dd9b77',
        canonicalExpression: 'θ',
      },
    ],
  },
  {
    id: 'weave',
    title: 'Weave',
    blurb: 'A second polar spiral shows how theta can scale the whole path, not just place it.',
    accent: '#d68c6e',
    world: { x: 3480, y: -520 },
    coordinateMode: 'polar',
    equationPrefix: 'r',
    parameterDomain: { min: 0, max: 1.5708, tickStep: 0.3927 },
    axes: {
      x: { min: -1, max: 3.4, tickStep: 1 },
      y: { min: -0.5, max: 3.3, tickStep: 0.5 },
    },
    equation: [
      { type: 'slot', slotId: 'radius' },
      { type: 'slot', slotId: 'theta' },
    ],
    slots: [
      { id: 'radius', allowedTiles: ['2'], label: 'radius factor' },
      { id: 'theta', allowedTiles: ['θ'], label: 'theta input' },
    ],
    goals: [
      {
        id: 'path-cellar',
        label: 'Open the cellar',
        shape: 'heart',
        edge: 'top',
        min: -0.2,
        max: 0.2,
        unlocks: ['cellar'],
        color: '#d78c70',
        canonicalExpression: '2θ',
      },
    ],
  },
  {
    id: 'cellar',
    title: 'Cellar',
    blurb: 'One last cartesian revisit mixes a squared term inside parentheses and a final division.',
    accent: '#d58b77',
    world: { x: 3210, y: 30 },
    axes: {
      x: { min: 0, max: 5, tickStep: 1 },
      y: { min: 0, max: 4.2, tickStep: 0.5 },
    },
    equation: [
      { type: 'fixed', value: '(' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '2', displayStyle: 'superscript' },
      { type: 'fixed', value: '-' },
      { type: 'slot', slotId: 'drop' },
      { type: 'fixed', value: ')' },
      { type: 'fixed', value: '/' },
      { type: 'fixed', value: '5' },
    ],
    slots: [{ id: 'drop', allowedTiles: ['5'], label: 'drop' }],
    goals: [
      {
        id: 'path-finale',
        label: 'Open the finale',
        shape: 'circle',
        edge: 'right',
        min: 3.9,
        max: 4.1,
        unlocks: ['finale'],
        color: '#d69280',
        canonicalExpression: '(x^2 - 5) / 5',
      },
    ],
  },
  {
    id: 'finale',
    title: 'Finale',
    blurb: 'The finale folds logarithms, parentheses, and exponents into one last elegant target.',
    accent: '#c78882',
    world: { x: 2640, y: 400 },
    axes: {
      x: { min: 0, max: 4.6, tickStep: 1 },
      y: { min: 0, max: 2.2, tickStep: 0.5 },
    },
    equation: [
      { type: 'fixed', value: 'log' },
      { type: 'fixed', value: '5', displayStyle: 'subscript' },
      { type: 'fixed', value: '(' },
      { type: 'fixed', value: 'x' },
      { type: 'fixed', value: '2', displayStyle: 'superscript' },
      { type: 'fixed', value: '+' },
      { type: 'slot', slotId: 'lift' },
      { type: 'fixed', value: ')' },
    ],
    slots: [{ id: 'lift', allowedTiles: ['5'], label: 'lift' }],
    goals: [
      {
        id: 'path-victory',
        label: 'Finish the whole world',
        shape: 'star',
        edge: 'top',
        min: 4.45,
        max: 4.55,
        unlocks: [],
        color: '#cf8b8e',
        canonicalExpression: 'log_5(x^2 + 5)',
      },
    ],
  },
]

assertUniqueGoalSolutions(SECTIONS)
